#!/usr/bin/env php
<?php

namespace Lantern;

/*
|--------------------------------------------------------------------------
| Pre-boot: Set storage to app/uploads
|--------------------------------------------------------------------------
|
| Overloading Lumen defaults to run in a novel environment.
|
*/

$🛄 = require 'storage.php';

/*
|--------------------------------------------------------------------------
| Boot: Boot lantern
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

$🎃 = include 'lantern.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $🎃->make('\Illuminate\Contracts\Console\Kernel');

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
